import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";
import Footer from "@/components/Footer";

export default function Terms() {
  return (
    <div className="min-h-screen flex flex-col bg-background">
      {/* Header */}
      <header className="border-b border-border">
        <div className="container py-4">
          <Link href="/" className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-4 w-4" />
            <span>Back to Home</span>
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 container py-12 max-w-3xl">
        <h1 className="text-3xl font-bold text-foreground mb-8">Terms of Service</h1>
        
        <div className="prose prose-neutral max-w-none space-y-6">
          <p className="text-muted-foreground leading-relaxed">
            Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">1. No Legal Advice</h2>
            <p className="text-muted-foreground leading-relaxed">
              ContractRedFlag is an informational tool designed to help users identify potential 
              areas of concern in contracts. <strong className="text-foreground">This service does not constitute legal advice, 
              legal representation, or attorney-client relationship.</strong> The analysis provided 
              is generated by artificial intelligence and should not be relied upon as a substitute 
              for professional legal counsel.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">2. Informational Purpose Only</h2>
            <p className="text-muted-foreground leading-relaxed">
              All content, analysis, and results provided by ContractRedFlag are for informational 
              and educational purposes only. The tool is designed to highlight potential areas of 
              concern in contract language, but it cannot replace the judgment and expertise of a 
              qualified legal professional. Users should always consult with a licensed attorney 
              before making legal decisions or signing contracts.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">3. No Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              ContractRedFlag, its owners, operators, and affiliates shall not be held liable for 
              any damages, losses, or consequences arising from the use of this service. This includes, 
              but is not limited to, direct, indirect, incidental, consequential, or punitive damages 
              resulting from reliance on the analysis provided. Users acknowledge that they use this 
              service at their own risk.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">4. Accuracy Disclaimer</h2>
            <p className="text-muted-foreground leading-relaxed">
              While we strive to provide accurate and helpful analysis, ContractRedFlag cannot 
              guarantee the completeness, accuracy, or reliability of the results. AI-generated 
              analysis may contain errors, omissions, or misinterpretations. Users should independently 
              verify all information and seek professional legal advice for important matters.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">5. Payment Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              Payment for full analysis is processed securely through Stripe. All payments are 
              one-time charges and are non-refundable unless otherwise required by applicable law. 
              By making a payment, you agree to these terms and acknowledge the limitations of the service.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-xl font-semibold text-foreground">6. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to modify these terms at any time. Continued use of the service 
              after changes constitutes acceptance of the modified terms.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
